apiVersion: v1
kind: deployment
metadata:
  - name: mysql
spec: 
  ports:
  - name:  mysql-port
    port:  3306
    protocol: TCP
  selector:
    app: mysql
  clusterIP: none
---

apiVersion: apps/v1
kind: deployment
metadata:
  labels:
    app: mysql