apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ken-app-deployment
  labels:
    app: nginx

spec:
  replicas: 4
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: ken-doc-app
          image: nginx:1.20.0
          ports:
            - name: ken-doc-port
              containerPort: 80
              protocol: TCP
