apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depolyment

spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metedata:
      labels:
        component: server  
    spec:
      containers:
        - name:  server-deply-container
          image:  stephengrider/multi-server
          ports:
            - containerPort: 5000
