apiVersion: v1
kind: Service
metadata:
  name: client-deployment
spec:
  type: ClusterIP
  selector:
    component: ken
  ports:
    - name: client-cluster-node-port
      port: 3000
      targetPort: 3000
