apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: nginx-srv-port
      nodePort: 30007
    - name: https
      protocol: TCP
      port: 443
      targetPort: nginx-srv-port
      nodePort: 30008

