apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-nginx-web
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: nginx-web
