apiVersion: v1
kind: Service
metadata:
  name: server-deployment
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - name: server-cluster-node-port
      port: 5000
      targetPort: 5000
