apiVersion: v1
kind: Pod
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  containers:
  - name: hello-node
    image: ealen/echo-server:latest  # ✅ Updated image
    ports:
    - containerPort: 80
